# Generated by Django 4.2 on 2023-06-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
