# Generated by Django 4.2.2 on 2023-07-10 22:23

from django.db import migrations
from django.utils.text import slugify


def up(apps, schema_editor):
    Category = apps.get_model('products', 'Category')
    for category in Category.objects.iterator():
        category.slug = slugify(category.name)
        #  only for slug field
        category.save(update_fields=('slug',))


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_is_manual_slug_category_slug'),
    ]

    operations = [
        migrations.RunPython(up, reverse_code=migrations.RunPython.noop)
    ]
